name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -S tests -B build

      - name: Build tests
        run: cmake --build build

      - name: Run tests
        run: cd build && ctest --output-on-failure